# Generated by Django 6.0.4 on 2026-04-19 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_initial'),
        ('interactions', '0003_remove_discussion_booking_message_sender_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='interactions.message'),
        ),
    ]
