# Generated by Django 6.0.4 on 2026-04-14 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('districts', '0001_initial'),
        ('interactions', '0001_initial'),
        ('services', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='users.client'),
        ),
        migrations.AddField(
            model_name='booking',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='districts.district'),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='services.serviceitem'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.artist'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discussion', to='interactions.booking'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.client'),
        ),
        migrations.AddField(
            model_name='histoetatbooking',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='interactions.booking'),
        ),
        migrations.AddField(
            model_name='message',
            name='discussion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='interactions.discussion'),
        ),
        migrations.AddField(
            model_name='review',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.artist'),
        ),
        migrations.AddField(
            model_name='review',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='interactions.booking'),
        ),
    ]
