# Generated by Django 6.0.4 on 2026-04-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='booking',
        ),
        migrations.AddField(
            model_name='message',
            name='sender_id',
            field=models.IntegerField(default=101),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='viewed_by_receiver',
            field=models.BooleanField(default=False),
        ),
    ]
