name: Keep Render Awake

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render app
        run: |
          echo "Pinging at $(date)"
          curl -s -o /dev/null -w "%{http_code}" https://houmti-tn-back.onrender.com